vich_uploader:
    db_driver: orm
    mappings:
        attachments:
            uri_prefix: /upload/attachments
            upload_destination: '%kernel.project_dir%/public/upload/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        presentations:
            uri_prefix: /upload/presentations
            upload_destination: '%kernel.project_dir%/public/upload/presentations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer