framework:
    mailer:
        # this disables delivery of messages entirely
        transports:
            main: '%env(MAILER_DSN)%'
            alternative: '%env(MAILER_DSN_IMPORTANT)%'
        envelope:
            sender: 'lepskaadasha@gmail.com'